remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
title: Your Site Title
author:
  name: Your Name
  avatar: /assets/images/profile.png # Place your profile image in assets/images
  bio: 'A brief description about you.'
  location: City, Country
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourtwitter"
    # Add more social links as needed
permalink: /:categories/:title/
