title: My Robotics Site
description: "A site about robotics and autonomous systems"
author:
  name: Your Name
  email: youremail@example.com
  bio: "Robotics enthusiast focused on autonomous systems, AI, and sensor fusion."

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site navigation
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
