# Site settings
title: My Robotics Site
author:
  name: Your Name
  bio: 'A robotics enthusiast focusing on autonomous systems and AI.'
  location: City, Country
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourtwitter"

# Theme setup
remote_theme: mmistakes/minimal-mistakes

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# SEO settings
description: "A site dedicated to robotics projects, research, and tutorials."
